// Anchors
const SEL_ANCHOR_PAGE_FIRST_CUSTOMER = "#anchorPageFirstCustomer"
const SEL_ANCHOR_PAGE_FIRST_EMPLOYEE = "#anchorPageFirstEmployee"
const SEL_ANCHOR_PAGE_FIRST_ITEM = "#anchorPageFirstItem"
const SEL_ANCHOR_PAGE_FIRST_ITEM_ORDER = "#anchorPageFirstItemOrder"
const SEL_ANCHOR_PAGE_FIRST_ORDER = "#anchorPageFirstOrder"
const SEL_ANCHOR_PAGE_LAST_CUSTOMER = "#anchorPageLastCustomer"
const SEL_ANCHOR_PAGE_LAST_EMPLOYEE = "#anchorPageLastEmployee"
const SEL_ANCHOR_PAGE_LAST_ITEM = "#anchorPageLastItem"
const SEL_ANCHOR_PAGE_LAST_ITEM_ORDER = "#anchorPageLastItemOrder"
const SEL_ANCHOR_PAGE_LAST_ORDER = "#anchorPageLastOrder"
const SEL_ANCHOR_PAGE_NEXT_CUSTOMER = "#anchorPageNextCustomer"
const SEL_ANCHOR_PAGE_NEXT_EMPLOYEE = "#anchorPageNextEmployee"
const SEL_ANCHOR_PAGE_NEXT_ITEM = "#anchorPageNextItem"
const SEL_ANCHOR_PAGE_NEXT_ITEM_ORDER = "#anchorPageNextItemOrder"
const SEL_ANCHOR_PAGE_NEXT_ORDER = "#anchorPageNextOrder"
const SEL_ANCHOR_PAGE_PREVIOUS_CUSTOMER = "#anchorPagePreviousCustomer"
const SEL_ANCHOR_PAGE_PREVIOUS_EMPLOYEE = "#anchorPagePreviousEmployee"
const SEL_ANCHOR_PAGE_PREVIOUS_ITEM = "#anchorPagePreviousItem"
const SEL_ANCHOR_PAGE_PREVIOUS_ITEM_ORDER = "#anchorPagePreviousItemOrder"
const SEL_ANCHOR_PAGE_PREVIOUS_ORDER = "#anchorPagePreviousOrder"

// Badges
const SEL_BADGE_TOTAL_CUSTOMERS = "#badgeTotalCustomers"
const SEL_BADGE_TOTAL_EMPLOYEES = "#badgeTotalEmployees"
const SEL_BADGE_TOTAL_ITEMS = "#badgeTotalItems"
const SEL_BADGE_TOTAL_ITEM_ORDER = "#badgeTotalItemOrder"
const SEL_BADGE_TOTAL_ORDERS = "#badgeTotalOrders"

//Buttons
const SEL_BUTTON_ADD_EMPLOYEE = "#buttonAddEmployee"
const SEL_BUTTON_ADD_ITEM = "#buttonAddItem"
const SEL_BUTTON_ADD_ITEM_ORDER = "#buttonAddItemOrder"
const SEL_BUTTON_ADD_ORDER = "#buttonAddOrder"
const SEL_BUTTON_CANCEL_CUSTOMER = "#buttonCancelCustomer"
const SEL_BUTTON_CANCEL_EMPLOYEE = "#buttonCancelEmployee"
const SEL_BUTTON_CANCEL_ITEM = "#buttonCancelItem"
const SEL_BUTTON_CANCEL_ITEM_ORDER = "#buttonCancelItemOrder"
const SEL_BUTTON_CANCEL_ORDER = "#buttonCancelOrder"
const SEL_BUTTON_REGISTER_CUSTOMER = "#buttonRegisterCustomer"
const SEL_BUTTON_SAVE_CUSTOMER = "#buttonSaveCustomer"
const SEL_BUTTON_SAVE_EMPLOYEE = "#buttonSaveEmployee"
const SEL_BUTTON_SAVE_ITEM = "#buttonSaveItem"
const SEL_BUTTON_SAVE_ITEM_ORDER = "#buttonSaveItemOrder"
const SEL_BUTTON_SAVE_ORDER = "#buttonSaveOrder"

// Forms
const SEL_FORM_CUSTOMER = "#formCustomer"
const SEL_FORM_EMPLOYEE = "#formEmployee"
const SEL_FORM_ITEM = "#formItem"
const SEL_FORM_ITEM_ORDER = "#formItemOrder"
const SEL_FORM_ORDER = "#formOrder"
const SEL_FORM_PAGINATION_CUSTOMER = "#formPaginationCustomer"
const SEL_FORM_PAGINATION_EMPLOYEE = "#formPaginationEmployee"
const SEL_FORM_PAGINATION_ITEM = "#formPaginationItem"
const SEL_FORM_PAGINATION_ITEM_ORDER = "#formPaginationItemOrder"
const SEL_FORM_PAGINATION_ORDER = "#formPaginationOrder"

// Headers
const SEL_HEADER_CUSTOMER_ACTIONS = "#headerCustomerActions"
const SEL_HEADER_CUSTOMER_ADDRESS = "#headerCustomerAddress"
const SEL_HEADER_CUSTOMER_FIRST_NAME = "#headerCustomerFirstName"
const SEL_HEADER_CUSTOMER_ID = "#headerCustomerId"
const SEL_HEADER_CUSTOMER_LAST_NAME = "#headerCustomerLastName"
const SEL_HEADER_CUSTOMER_PHONE_NUMBER = "#headerCustomerPhoneNumber"
const SEL_HEADER_EMPLOYEE_ACTIONS = "#headerEmployeeActions"
const SEL_HEADER_EMPLOYEE_FIRST_NAME = "#headerEmployeeFirstName"
const SEL_HEADER_EMPLOYEE_HIRE_DATE = "#headerEmployeeHireDate"
const SEL_HEADER_EMPLOYEE_ID = "#headerEmployeeId"
const SEL_HEADER_EMPLOYEE_LAST_NAME = "#headerEmployeeLastName"
const SEL_HEADER_EMPLOYEE_PHONE_NUMBER = "#headerEmployeePhoneNumber"
const SEL_HEADER_ITEM_ACTIONS = "#headerItemActions"
const SEL_HEADER_ITEM_ARTIST = "#headerItemArtist"
const SEL_HEADER_ITEM_AVAILABLE_QUANTITY = "#headerItemAvailableQuantity"
const SEL_HEADER_ITEM_FORMAT = "#headerItemFormat"
const SEL_HEADER_ITEM_GENRE = "#headerItemGenre"
const SEL_HEADER_ITEM_ID = "#headerItemId"
const SEL_HEADER_ITEM_ORDER_ACTIONS = "#headerItemOrderActions"
const SEL_HEADER_ITEM_ORDER_ID = "#headerItemOrderId"
const SEL_HEADER_ITEM_ORDER_ITEM_ID = "#headerItemOrderItemId"
const SEL_HEADER_ITEM_ORDER_ORDER_ID = "#headerItemOrderOrderId"
const SEL_HEADER_ITEM_ORDER_QUANTITY = "#headerItemOrderQuantity"
const SEL_HEADER_ITEM_PRICE = "#headerItemPrice"
const SEL_HEADER_ITEM_RELEASE_DATE = "#headerItemReleaseDate"
const SEL_HEADER_ITEM_TITLE = "#headerItemTitle"
const SEL_HEADER_ORDER_ACTIONS = "#headerOrderActions"
const SEL_HEADER_ORDER_CUSTOMER = "#headerOrderCustomer"
const SEL_HEADER_ORDER_DATE = "#headerOrderDate"
const SEL_HEADER_ORDER_EMPLOYEE = "#headerOrderEmployee"
const SEL_HEADER_ORDER_ID = "#headerOrderId"
const SEL_HEADER_ORDER_PAYMENT_METHOD = "#headerOrderPaymentMethod"

// Inputs
const SEL_INPUT_CURRENT_PAGE_CUSTOMER = "#inputCurrentPageCustomer"
const SEL_INPUT_CURRENT_PAGE_EMPLOYEE = "#inputCurrentPageEmployee"
const SEL_INPUT_CURRENT_PAGE_ITEM = "#inputCurrentPageItem"
const SEL_INPUT_CURRENT_PAGE_ITEM_ORDER = "#inputCurrentPageItemOrder"
const SEL_INPUT_CURRENT_PAGE_ORDER = "#inputCurrentPageOrder"
const SEL_INPUT_CUSTOMER_CITY = "#inputCustomerCity"
const SEL_INPUT_CUSTOMER_FIRST_NAME = "#inputCustomerFirstName"
const SEL_INPUT_CUSTOMER_LAST_NAME = "#inputCustomerLastName"
const SEL_INPUT_CUSTOMER_PHONE_NUMBER = "#inputCustomerPhoneNumber"
const SEL_INPUT_CUSTOMER_POSTAL_CODE = "#inputCustomerPostalCode"
const SEL_INPUT_CUSTOMER_ROAD = "#inputCustomerRoad"
const SEL_INPUT_EMPLOYEE_FIRST_NAME = "#inputEmployeeFirstName"
const SEL_INPUT_EMPLOYEE_HIRE_DATE = "#inputEmployeeHireDate"
const SEL_INPUT_EMPLOYEE_LAST_NAME = "#inputEmployeeLastName"
const SEL_INPUT_EMPLOYEE_PHONE_NUMBER = "#inputEmployeePhoneNumber"
const SEL_INPUT_ITEM_ARTIST = "#inputItemArtist"
const SEL_INPUT_ITEM_AVAILABLE_QUANTITY = "#inputItemAvailableQuantity"
const SEL_INPUT_ITEM_ORDER_QUANTITY = "#inputItemOrderQuantity"
const SEL_INPUT_ITEM_PRICE = "#inputItemPrice"
const SEL_INPUT_ITEM_RELEASE_DATE = "#inputItemReleaseDate"
const SEL_INPUT_ITEM_TITLE = "#inputItemTitle"
const SEL_INPUT_ORDER_DATE = "#inputOrderDate"

// Labels
const SEL_LABEL_CUSTOMER_CITY = "#labelCustomerCity"
const SEL_LABEL_CUSTOMER_FIRST_NAME = "#labelCustomerFirstName"
const SEL_LABEL_CUSTOMER_LAST_NAME = "#labelCustomerLastName"
const SEL_LABEL_CUSTOMER_PHONE_NUMBER = "#labelCustomerPhoneNumber"
const SEL_LABEL_CUSTOMER_POSTAL_CODE = "#labelCustomerPostalCode"
const SEL_LABEL_CUSTOMER_PROVINCE = "#labelCustomerProvince"
const SEL_LABEL_CUSTOMER_ROAD = "#labelCustomerRoad"
const SEL_LABEL_EMPLOYEE_FIRST_NAME = "#labelEmployeeFirstName"
const SEL_LABEL_EMPLOYEE_HIRE_DATE = "#labelEmployeeHireDate"
const SEL_LABEL_EMPLOYEE_LAST_NAME = "#labelEmployeeLastName"
const SEL_LABEL_EMPLOYEE_PHONE_NUMBER = "#labelEmployeePhoneNumber"
const SEL_LABEL_ITEM_ARTIST = "#labelItemArtist"
const SEL_LABEL_ITEM_AVAILABLE_QUANTITY = "#labelItemAvailableQuantity"
const SEL_LABEL_ITEM_FORMAT = "#labelItemFormat"
const SEL_LABEL_ITEM_GENRE = "#labelItemGenre"
const SEL_LABEL_ITEM_ORDER_ITEM_ID = "#labelItemOrderItemId"
const SEL_LABEL_ITEM_ORDER_ORDER_ID = "#labelItemOrderOrderId"
const SEL_LABEL_ITEM_ORDER_QUANTITY = "#labelItemOrderQuantity"
const SEL_LABEL_ITEM_PRICE = "#labelItemPrice"
const SEL_LABEL_ITEM_RELEASE_DATE = "#labelItemReleaseDate"
const SEL_LABEL_ITEM_TITLE = "#labelItemTitle"
const SEL_LABEL_ORDER_CUSTOMER = "#labelOrderCustomer"
const SEL_LABEL_ORDER_DATE = "#labelOrderDate"
const SEL_LABEL_ORDER_EMPLOYEE = "#labelOrderEmployee"
const SEL_LABEL_ORDER_PAYMENT_METHOD = "#labelOrderPaymentMethod"

// Navigation links
const SEL_NAV_LINK_ADMINISTRATION = "#navLinkAdministration"
const SEL_NAV_LINK_CUSTOMER = "#navLinkCustomer"
const SEL_NAV_LINK_INVENTORY = "#navLinkInventory"
const SEL_NAV_LINK_ITEM_ORDER = "#navLinkItemOrder"
const SEL_NAV_LINK_ORDER = "#navLinkOrder"

// Pagination
const SEL_PAGE_FIRST_CUSTOMER = "#pageFirstCustomer"
const SEL_PAGE_FIRST_EMPLOYEE = "#pageFirstEmployee"
const SEL_PAGE_FIRST_ITEM = "#pageFirstItem"
const SEL_PAGE_FIRST_ITEM_ORDER = "#pageFirstItemOrder"
const SEL_PAGE_FIRST_ORDER = "#pageFirstOrder"
const SEL_PAGE_LAST_CUSTOMER = "#pageLastCustomer"
const SEL_PAGE_LAST_EMPLOYEE = "#pageLastEmployee"
const SEL_PAGE_LAST_ITEM = "#pageLastItem"
const SEL_PAGE_LAST_ITEM_ORDER = "#pageLastItemOrder"
const SEL_PAGE_LAST_ORDER = "#pageLastOrder"
const SEL_PAGE_NEXT_CUSTOMER = "#pageNextCustomer"
const SEL_PAGE_NEXT_EMPLOYEE = "#pageNextEmployee"
const SEL_PAGE_NEXT_ITEM = "#pageNextItem"
const SEL_PAGE_NEXT_ITEM_ORDER = "#pageNextItemOrder"
const SEL_PAGE_NEXT_ORDER = "#pageNextOrder"
const SEL_PAGE_PREVIOUS_CUSTOMER = "#pagePreviousCustomer"
const SEL_PAGE_PREVIOUS_EMPLOYEE = "#pagePreviousEmployee"
const SEL_PAGE_PREVIOUS_ITEM = "#pagePreviousItem"
const SEL_PAGE_PREVIOUS_ITEM_ORDER = "#pagePreviousItemOrder"
const SEL_PAGE_PREVIOUS_ORDER = "#pagePreviousOrder"

// Screens
const SEL_SCREEN_ADMINISTRATION = "#screenAdministration"
const SEL_SCREEN_CUSTOMER = "#screenCustomer"
const SEL_SCREEN_CUSTOMER_FORM = "#screenCustomerForm"
const SEL_SCREEN_EMPLOYEE_FORM = "#screenEmployeeForm"
const SEL_SCREEN_INVENTORY = "#screenInventory"
const SEL_SCREEN_ITEM_FORM = "#screenItemForm"
const SEL_SCREEN_ITEM_ORDER = "#screenItemOrder"
const SEL_SCREEN_ITEM_ORDER_FORM = "#screenItemOrderForm"
const SEL_SCREEN_ORDER = "#screenOrder"
const SEL_SCREEN_ORDER_FORM = "#screenOrderForm"

// Selects
const SEL_SELECT_CUSTOMER_PROVINCE = "#selectCustomerProvince"
const SEL_SELECT_ITEM_FORMAT = "#selectItemFormat"
const SEL_SELECT_ITEM_GENRE = "#selectItemGenre"
const SEL_SELECT_ITEM_ORDER_ITEM_ID = "#selectItemOrderItemId"
const SEL_SELECT_ITEM_ORDER_ORDER_ID = "#selectItemOrderOrderId"
const SEL_SELECT_ORDER_CUSTOMER = "#selectOrderCustomer"
const SEL_SELECT_ORDER_EMPLOYEE = "#selectOrderEmployee"
const SEL_SELECT_ORDER_PAYMENT_METHOD = "#selectOrderPaymentMethod"

// Spans
const SEL_SPAN_END_PAGE_CUSTOMER = "#spanEndPageCustomer"
const SEL_SPAN_END_PAGE_EMPLOYEE = "#spanEndPageEmployee"
const SEL_SPAN_END_PAGE_ITEM = "#spanEndPageItem"
const SEL_SPAN_END_PAGE_ITEM_ORDER = "#spanEndPageItemOrder"
const SEL_SPAN_END_PAGE_ORDER = "#spanEndPageOrder"
const SEL_SPAN_TOTAL_CUSTOMERS = "#spanTotalCustomers"
const SEL_SPAN_TOTAL_EMPLOYEES = "#spanTotalEmployees"
const SEL_SPAN_TOTAL_ITEMS = "#spanTotalItems"
const SEL_SPAN_TOTAL_ITEM_ORDERS = "#spanTotalItemOrders"
const SEL_SPAN_TOTAL_ORDERS = "#spanTotalOrders"

// Tables
const SEL_TABLE_BODY_CUSTOMER = "#tableCustomer tbody"
const SEL_TABLE_BODY_EMPLOYEE = "#tableEmployee tbody"
const SEL_TABLE_BODY_ITEM = "#tableItem tbody"
const SEL_TABLE_BODY_ITEM_ORDER = "#tableItemOrder tbody"
const SEL_TABLE_BODY_ORDER = "#tableOrder tbody"

// Title
const SEL_TITLE_ADMINISTRATION_SCREEN = "#titleAdministrationScreen"
const SEL_TITLE_APPLICATION = "title"
const SEL_TITLE_CUSTOMER_FORM_SCREEN = "#titleCustomerFormScreen"
const SEL_TITLE_CUSTOMER_SCREEN = "#titleCustomerScreen"
const SEL_TITLE_EMPLOYEE_FORM_SCREEN = "#titleEmployeeFormScreen"
const SEL_TITLE_INVENTORY_SCREEN = "#titleInventoryScreen"
const SEL_TITLE_ITEM_FORM_SCREEN = "#titleItemFormScreen"
const SEL_TITLE_ITEM_ORDER_FORM_SCREEN = "#titleItemOrderFormScreen"
const SEL_TITLE_ITEM_ORDER_SCREEN = "#titleItemOrderScreen"
const SEL_TITLE_ORDER_FORM_SCREEN = "#titleOrderFormScreen"
const SEL_TITLE_ORDER_SCREEN = "#titleOrderScreen"